### PR TITLE
Storing info on specific kind of observations ("hellinghoek")

### PR DESCRIPTION
**Pull request by reinout**
From the changelog:

- Added ``bin/bin/ribxdebug`` helper tool to print the info parsed from a
  .ribx file.

- Added parsing of angle observarions ("hellinghoek") as that's needed for a
  quality checker.

  Previously, observations were only inspected for their media files. This is
  the first observation we're looking at in more depth. (Which means the
  implementation might change later on).

### CODE REVIEW

**Comment by reinout** [comment]
Hm.... ik ben nog wat wijzigingen aan het aanbrengen...

**Comment by jackieleng** [comment]
oke.

**Comment by reinout** [comment]
@jackieleng: het is wat eenvoudiger geworden. Nu is 'ie wel klaar.

De specifieke checks komen in lizard-progress.

**Comment by reinout** [comment]
@jackieleng: I'm merging the changes (needed for Almere), but a review is still needed/handy :-)

**Pull request merged**
